// lex.yy.cpp generated by reflex 1.4.3 from quack.lxx

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_YYLTYPE             yy::location
#define REFLEX_OPTION_YYSTYPE             yy::parser::semantic_type
#define REFLEX_OPTION_bison_cc            true
#define REFLEX_OPTION_bison_cc_namespace  yy
#define REFLEX_OPTION_bison_cc_parser     parser
#define REFLEX_OPTION_bison_locations     true
#define REFLEX_OPTION_lex                 yylex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_namespace           yy
#define REFLEX_OPTION_noyywrap            true
#define REFLEX_OPTION_outfile             "lex.yy.cpp"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top{ user code %}                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 1 "quack.lxx"

/* Quack scanner
 *
 * 2018 Fall version for RE/flex,
 * skeleton.
 *
 */

#include "quack.tab.hxx"  /* Generated by bison. */
#include "Messages.h"


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/abslexer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace yy {

class Lexer : public reflex::AbstractLexer<reflex::Matcher> {
 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  Lexer(
      const reflex::Input& input = reflex::Input(),
      std::ostream&        os    = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  static const int comment = 1;
  static const int linecomment = 2;
  virtual void yylloc_update(yy::location& yylloc)
  {
    yylloc.begin.line = static_cast<unsigned int>(matcher().lineno());
    yylloc.begin.column = static_cast<unsigned int>(matcher().columno());
    yylloc.end.line = static_cast<unsigned int>(yylloc.begin.line + matcher().lines() - 1);
    yylloc.end.column = static_cast<unsigned int>(yylloc.begin.column + matcher().columns() - 1);
  }
  virtual int yylex(yy::parser::semantic_type *lvalp, yy::location *llocp)
  {
    return yylex(*lvalp, *llocp);
  }
  virtual int yylex(yy::parser::semantic_type& yylval, yy::location& yylloc);
};

} // namespace yy

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %{ user code %}                                                //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 13 "quack.lxx"

/* Externally visible file name --
* for error messages.
* FIXME: Need to extract this from structures that reflex passes
* or else find another way to dig it out.
*/
std::string yyfilename = "What file is this, anyway?";

/* Some strings can't be matched in one gulp.  We need
 * a buffer in which to assemble them from parts.
 */
std::string string_buf = "";

void yyerror (const std::string &msg, yy::position* where) {
     std::cout << where << ": " << msg;
}

/* Some long messages that don't fit well in the code below */

std::string BAD_ESC_MSG =
  "Illegal escape code; only \\\\, \\0, \\t, \\n, \\r, \\n are permitted";
std::string BAD_NL_STR =
  "Unclosed string?  Encountered newline in quoted string.";


#line 43 "quack.lxx"
/* You'll probably want scanner states for both multi-line
   * comments and for triple-quote strings.  Do comments first,
   * because they're easier (you just throw away the text).  Then
   * do triple-quote strings.  You might consider doing the same for
   * normal strings with a single pair of double quotes, to avoid
   * writing a really ugly regex.  'comment' here is an example of
   * how to declare an exclusive scanner state.
   */

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  BISON C++                                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

int yy::Lexer::yylex(yy::parser::semantic_type& yylval, yy::location& yylloc)
{
  static const char *REGEX_INITIAL = "(?m)(==)|([<]=)|([>]=)|([*+\\x2d/=\\x5b\\x7b\\x7d],.;<>])|(class)|(def)|(if)|(elif)|(else)|(return)|(while)|(typecase)|(string)|(Int)|(Obj)|(Boolean)|(true)|(false)|(and)|(or)|(not)|(Nothing)|(none)|([0-9]+)|([A-Z_a-z][0-9A-Z_a-z]*)|([\\x09\\x0a\\x20]*)|([/][\\x2a])|([/][/])|(.)";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  static const char *REGEX_comment = "(?m)([^\\x2a]*)|([\\x2a][^/])|([\\x2a][/])";
  static const reflex::Pattern PATTERN_comment(REGEX_comment);
  static const char *REGEX_linecomment = "(?m)(\\n)";
  static const reflex::Pattern PATTERN_linecomment(REGEX_linecomment);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  switch (start())
  {
    case INITIAL:
#line 61 "quack.lxx"
/* We start with some tokens that are not value-bearing,
   * i.e., the parser needs to know only which token was matched.
   */

  /* Multi-character punctuation with names */
    break;
  }
  while (true)
  {
    switch (start())
    {
      case INITIAL:
        matcher().pattern(PATTERN_INITIAL);
        matcher().scan();
        yylloc_update(yylloc);
        switch (matcher().accept())
        {
          case 0:
            if (matcher().at_end())
            {
#line 151 "quack.lxx"
{ return EOF; }

            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule at line 61: ==
#line 61 "quack.lxx"
{ return parser::token::EQUALS; }
            break;
          case 2: // rule at line 62: [<]=
#line 62 "quack.lxx"
{ return parser::token::ATMOST; }
            break;
          case 3: // rule at line 63: [>]=
#line 63 "quack.lxx"
{ return parser::token::ATLEAST;}


   /* Single character punctuation.  Because a character
    * in C or C++ can be treated as an integer, Bison lets
    * us return a character as a token.
    * JFlex/Cup do not let you do this in Java.
    * Here are a few ... there are more.
    */
            break;
          case 4: // rule at line 72: [*+\x2d/=\x5b\x7b\x7d],.;<>]
#line 72 "quack.lxx"
{ return text()[0]; }

  /* Keywords are essentially another kind of punctuation,
   * but since they also match the identifier pattern, we
   * need to be sure we give their patterns *before* the
   * identifier pattern.  Most scanner generators work this
   * way, but WARNING for Python PLY users:  PLY prioritizes
   * by length of the regular expression!
   * Here are a couple of examples.
   */

            break;
          case 5: // rule at line 83: class
#line 83 "quack.lxx"
{ return parser::token::CLASS; }
            break;
          case 6: // rule at line 84: def
#line 84 "quack.lxx"
{ return parser::token::DEF; }
            break;
          case 7: // rule at line 85: if
#line 85 "quack.lxx"
{ return parser::token::IF;}
            break;
          case 8: // rule at line 86: elif
#line 86 "quack.lxx"
{return parser::token::ELIF;}
            break;
          case 9: // rule at line 87: else
#line 87 "quack.lxx"
{return parser::token::ELSE;}
            break;
          case 10: // rule at line 88: return
#line 88 "quack.lxx"
{return parser::token::RETURN;}
            break;
          case 11: // rule at line 89: while
#line 89 "quack.lxx"
{return parser::token::WHILE;}
            break;
          case 12: // rule at line 90: typecase
#line 90 "quack.lxx"
{return parser::token::TYPECASE;}


  /* predefined identifiers */



            break;
          case 13: // rule at line 97: string
#line 97 "quack.lxx"
{return parser::token::STRING;}
            break;
          case 14: // rule at line 98: Int
#line 98 "quack.lxx"
{return parser::token::INT;}
            break;
          case 15: // rule at line 99: Obj
#line 99 "quack.lxx"
{return parser::token::OBJ;}
            break;
          case 16: // rule at line 100: Boolean
#line 100 "quack.lxx"
{return parser::token::BOOLEAN;}
            break;
          case 17: // rule at line 101: true
#line 101 "quack.lxx"
{return parser::token::TRUE;}
            break;
          case 18: // rule at line 102: false
#line 102 "quack.lxx"
{return parser::token::FALSE;}
            break;
          case 19: // rule at line 103: and
#line 103 "quack.lxx"
{return parser::token::AND;}
            break;
          case 20: // rule at line 104: or
#line 104 "quack.lxx"
{return parser::token::OR;}
            break;
          case 21: // rule at line 105: not
#line 105 "quack.lxx"
{return parser::token::NOT;}
            break;
          case 22: // rule at line 106: Nothing
#line 106 "quack.lxx"
{return parser::token::NOTHING;}
            break;
          case 23: // rule at line 107: none
#line 107 "quack.lxx"
{return parser::token::NONE;}




   /* The following tokens are value-bearing:
    * We pass a value back to the parser by copying
    * it into the yylval parameter.  The parser
    * expects string values for identifiers and
    * string literals in yylval.str.  It expects integer
    * values for integer literals in yylval.num.
    * I'll give pattern for integer literals.
    * You'll need another for identifiers.  Remember to
    * 'strdup' the value returned by 'text()', or else it will
    * be clobbered by subsequent calls.
    */

            break;
          case 24: // rule at line 124: [0-9]+
#line 124 "quack.lxx"
{ yylval.num = atoi(text()); return parser::token::INT_LIT; }
            break;
          case 25: // rule at line 125: [A-Z_a-z][0-9A-Z_a-z]*
#line 125 "quack.lxx"
{yylval.num=atoi(text()); return parser::token::IDENT;}
  /* You *can* write a one-line regular expression for matching a quoted string,
   * but you probably can't read it.  (I can't read mine.)  Scanner states and
   * simpler patterns are probably a better idea.
   * You almost certainly scanner states for triple quotes.
   * The tricky bit is catching errors, such as disallowed escape sequences
   * and unclosed quotes.
   */

  /* Ignore whitespace */
            break;
          case 26: // rule at line 135: [\x09\x0a\x20]*
#line 135 "quack.lxx"
{ ; }

   /* Multi-line comments */
            break;
          case 27: // rule at line 138: [/][\x2a]
#line 138 "quack.lxx"
{ start(comment); }
            break;
          case 28: // rule at line 143: [/][/]
#line 143 "quack.lxx"
{start(linecomment);}
            break;
          case 29: // rule at line 146: .
#line 146 "quack.lxx"
{   report::error("Unexpected character '" + std::string(text()) + "'" +
       " at line " + std::to_string(lineno()) +
       ", column " + std::to_string(columno()));
   }

            break;
        }
        break;
      case comment:
        matcher().pattern(PATTERN_comment);
        matcher().scan();
        yylloc_update(yylloc);
        switch (matcher().accept())
        {
          case 0:
            if (matcher().at_end())
            {
#line 151 "quack.lxx"
{ return EOF; }

            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule at line 139: [^\x2a]*
#line 139 "quack.lxx"
{ ; }
            break;
          case 2: // rule at line 140: [\x2a][^/]
#line 140 "quack.lxx"
{ ; }
            break;
          case 3: // rule at line 141: [\x2a][/]
#line 141 "quack.lxx"
{ start(INITIAL); }

            break;
        }
        break;
      case linecomment:
        matcher().pattern(PATTERN_linecomment);
        matcher().scan();
        yylloc_update(yylloc);
        switch (matcher().accept())
        {
          case 0:
            if (matcher().at_end())
            {
#line 151 "quack.lxx"
{ return EOF; }

            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule at line 144: \n
#line 144 "quack.lxx"
{ start(INITIAL);}

            break;
        }
        break;
      default:
        start(0);
    }
  }
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 3: user code                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 154 "quack.lxx"

/* No main program here */

